name: Build CustomItemsAPI

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:
    # allows manual trigger

jobs:
  build:
    runs-on: windows-latest
    
    #LabAPI references
    env:
      REFERENCES_URL: https://exslmod-team.github.io/SL-References/LabAPI.zip
      REFERENCES_PATH: ${{ github.workspace }}/References
      MAINPATH: CustomItemsAPI/CustomItemsAPI.csproj
      TESTPATH: CustomItemsAPI.TestItems/CustomItemsAPI.TestItems.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4.0.1

      - name: Download References
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.REFERENCES_URL }} -OutFile "${{ github.workspace }}/References.zip"
          Expand-Archive -Path "${{ github.workspace }}/References.zip" -DestinationPath ${{ env.REFERENCES_PATH }}

      - name: Build Main
        env:
          SL_REFERENCES: ${{ env.REFERENCES_PATH }}
        shell: pwsh
        run: |
          dotnet build ${{ env.MAINPATH }} -c Release -o:Main

      - name: Upload Main artifact
        uses: actions/upload-artifact@v4
        with:
          name: CustomItemsAPI
          path: Main
          if-no-files-found: error

      - name: Build Package
        env:
          SL_REFERENCES: ${{ env.REFERENCES_PATH }}
        shell: pwsh
        run: |
          dotnet pack ${{ env.MAINPATH }} -c Release -o:PKG

      - name: Upload Nuget package artifact
        uses: actions/upload-artifact@v4
        with:
          name: CustomItemsAPI Nuget package
          path: PKG/*.nupkg
          if-no-files-found: error

      - name: Build Test
        env:
          SL_REFERENCES: ${{ env.REFERENCES_PATH }}
        shell: pwsh
        run: |
          dotnet build ${{ env.TESTPATH }} -c Release -o:Test

      - name: Upload Test artifact
        uses: actions/upload-artifact@v4
        with:
          name: CustomItemsAPI.TestItems
          path: Test
          if-no-files-found: error
